### ISSUE TITLE
Installation - header complaints by WP

### ISSUE THREAD

**Issue by matthewc100** [bpiwowar/papercite#147] opened 2020-03-09 02:24 UTC
After activation, I got the following:

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /---server---/sl.coblentz/libraries/libraries/wp-content/plugins/papercite/papercite.classes.php on line 485

Warning: Cannot modify header information - headers already sent by (output started at /---server---/sl.coblentz/libraries/libraries/wp-content/plugins/papercite/papercite.classes.php:485) in /hermes/bosnacweb02/bosnacweb02bf/b1369/sl.coblentz/libraries/libraries/wp-includes/functions.php on line 6029

Warning: Cannot modify header information - headers already sent by (output started at /---server---/sl.coblentz/libraries/libraries/wp-content/plugins/papercite/papercite.classes.php:485) in /hermes/bosnacweb02/bosnacweb02bf/b1369/sl.coblentz/libraries/libraries/wp-admin/includes/misc.php on line 1252

Warning: Cannot modify header information - headers already sent by (output started at /---server---/sl.coblentz/libraries/libraries/wp-content/plugins/papercite/papercite.classes.php:485) in /hermes/bosnacweb02/bosnacweb02bf/b1369/sl.coblentz/libraries/libraries/wp-admin/admin-header.php on line 9

Warning: Cannot modify header information - headers already sent by (output started at /---server---/sl.coblentz/libraries/libraries/wp-content/plugins/papercite/papercite.classes.php:485) in /hermes/bosnacweb02/bosnacweb02bf/b1369/sl.coblentz/libraries/libraries/wp-includes/option.php on line 961

Warning: Cannot modify header information - headers already sent by (output started at /---server---/sl.coblentz/libraries/libraries/wp-content/plugins/papercite/papercite.classes.php:485) in /hermes/bosnacweb02/bosnacweb02bf/b1369/sl.coblentz/libraries/libraries/wp-includes/option.php on line 962

```

(I deleted the actual server address - if you need it, message me at mcoblentz @ comcast.net). 

I can't tell if this is a big issue or not; but I thought I would bring it to your attention.
matt

**Comment by digfish** [comment] 2020-03-09 19:21
Hello @matthewc100 , thanks for letting us know this issue.
Can you please inform which PHP and Wordpress you are using ? 
In my local environment, I'm using PHP 7.3 with Wordpress 5.4, and I'm not able to reproduce the error. Anyone, since the warning message is very explicit, I've modified the line and committed to the github. Update your version with the one in the github: 
- `https://github.com/bpiwowar/papercite/archive/0.5.23.tar.gz` .
.I will update the plugin repo on Wordpress when after you successfully apply the update.

Best regards,
Samuel

**Comment by matthewc100** [comment] 2020-03-10 04:22
Hello Samuel,

I’m using PHP 7.3.2 and WP 5.3.2.  I have updated the plug-in and it installed & activated with no errors.  I’ll start playing with it and give you any feedback.  

 

Thanks for being so responsive on this.  I look forward to working with this a lot.

 

Matt

(I’m uploading/digitizing my master’s portfolio work.  Here’s a page: http://libraries.coblentzclan.com/libraries/my-eportfolio-in-information-science/library-plan-for-a-corporate-digital-library/)

**Comment by digfish** [comment] 2020-03-10 16:05
Updated repository in Wordpress Plugins directory.

**Closed by digfish** 2020-03-10 16:05 UTC

**Comment by AlexanderWillner** [comment] 2020-09-06 19:01
Some feedback / update here:
- Papercite: Version 0.5.22
- WordPress: Version 5.5.1
- PHP: Version 7.2.23 (OK), 7.3.6 (NOK)
- Message:  `Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /path/to/wordpress/wp-content/plugins/papercite/papercite.classes.php on line 485`
