### ISSUE TITLE
maximum size of bibtex database?

### ISSUE THREAD

**Issue by jvitku** [bpiwowar/papercite#91] opened 2014-09-10 18:05 UTC
Hi, just curious: is there any (estimate of) maximum size of bibtex database?

If I try to pass the papercite (using bibfilter command) the database with roughly 350 publications (with abstracts) it spits out the error:

 Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 28575 bytes) in  /srv/disk1/1427127/www/artificiallife.co.nf/wp-content/plugins/papercite/lib/BibTex_pear.php on line 330

After cutting it down to about 270 entries, everything works again. 
Thanks for info, 
Jarda

**Comment by sistlind** [comment] 2015-06-05 10:32
I am using a bibtex file with nearly 1600 entries without any problems (with and without db-cache), therefore, about 300 entries shouldn't be a problem

**Comment by bpiwowar** [comment] 2015-08-25 14:51
I will close this bug since I cannot reproduce it. Feel free to re-open with more details

**Closed by bpiwowar** 2015-08-25 14:51 UTC
